#!/bin/bash

# サービスアカウントキー作成手順スクリプト
# 使用方法: ./create-service-account.sh

echo "🔑 サービスアカウントキー作成手順を開始します..."

# プロジェクト設定
PROJECT_ID="justjoin-platform"

echo "📋 プロジェクト情報:"
echo "  プロジェクトID: $PROJECT_ID"

echo ""
echo "🔧 サービスアカウントキー作成手順:"
echo ""
echo "1. Google Cloud Consoleにアクセス:"
echo "   https://console.cloud.google.com/"
echo ""
echo "2. プロジェクトを選択: $PROJECT_ID"
echo ""
echo "3. IAM & Admin > Service Accounts に移動"
echo ""
echo "4. 'Create Service Account' をクリック"
echo ""
echo "5. サービスアカウントの詳細を入力:"
echo "   - Service account name: match-job-sa"
echo "   - Service account ID: match-job-sa"
echo "   - Description: Service account for Match Job application"
echo ""
echo "6. 'Create and Continue' をクリック"
echo ""
echo "7. 役割を追加:"
echo "   - Cloud SQL Client"
echo "   - Storage Object Admin"
echo "   - Cloud Run Invoker"
echo ""
echo "8. 'Continue' をクリック"
echo ""
echo "9. 'Done' をクリック"
echo ""
echo "10. 作成されたサービスアカウントをクリック"
echo ""
echo "11. 'Keys' タブをクリック"
echo ""
echo "12. 'Add Key' > 'Create new key' をクリック"
echo ""
echo "13. 'JSON' を選択して 'Create' をクリック"
echo ""
echo "14. ダウンロードされたファイルを 'google-credentials.json' として保存"
echo ""
echo "15. ファイルをプロジェクトルートに配置"
echo ""

echo "✅ サービスアカウントキー作成手順完了！"
echo ""
echo "📁 ファイル配置場所:"
echo "   ./google-credentials.json"
echo ""
echo "⚠️  注意事項:"
echo "1. ダウンロードしたファイルを安全に管理してください"
echo "2. ファイルをGitにコミットしないでください"
echo "3. .gitignoreに追加することをお勧めします"
echo ""
echo "🚀 次のステップ:"
echo "1. 上記手順でサービスアカウントキーを作成"
echo "2. google-credentials.jsonファイルを配置"
echo "3. ./check-setup.shを実行して設定を確認" 