import React, { createContext, useContext, useState, type ReactNode } from 'react';

export type Language = 'ja' | 'en' | 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ja: {
    // Header
    'header.login': 'ログイン',
    'header.register': '新規登録',
    
    // Hero
    'hero.title': '<span class="text-primary">日本での成長</span>を<br>実現するプラットフォーム',
    'hero.subtitle': '専任担当者が就職をサポート<br>最適な仕事が見つかります',
    'hero.stats.companies': '取引社数',
    'hero.stats.staff': '就業スタッフ',
    'hero.stats.prefectures': '都道府県対応',
    'hero.stats.note1': '※2023年度実績',
    'hero.stats.note2': '※2024年12月時点',
    'hero.stats.note3': '対応可能',
    'hero.quickInfo1': '簡単30秒',
    'hero.quickInfo2': '無料の転職サポートに登録',
    'hero.cta1': '転職したい',
    'hero.cta2': '情報収集したい',
    'hero.contact': 'お電話はこちら',
    'hero.contactHours': '平日 9:00~19:00 (土日祝を除く)',
    'hero.appeal.title': '働きたい人への訴求',
    'hero.appeal.subtitle': 'justjoinなら、あなたの希望に合った求人を見つけることができます',
    'hero.appeal.item1.title': '幅広い求人情報',
    'hero.appeal.item1.description': '事務・営業・研究開発・クリエイティブなど、様々な職種の求人を取り揃えています。',
    'hero.appeal.item2.title': '柔軟な働き方',
    'hero.appeal.item2.description': '短期・短時間からフルタイムまで、あなたのライフスタイルに合わせた働き方が可能です。',
    'hero.appeal.item3.title': '充実のサポート',
    'hero.appeal.item3.description': '専門のアドバイザーが、あなたの転職活動を徹底的にサポートします。',
    
    // Company Info
    'company.title': 'ABOUT US',
    'company.subtitle': 'justjoinについて',
    'company.name': '会社名',
    'company.nameValue': 'just join',
    'company.email': 'メールアドレス',
    'company.emailValue': 'inside.justjoin@gmail.com',
    'company.description': 'just joinは、求職者と企業をつなぐ求人プラットフォームを運営しています。',
    'company.description2': 'AI面接システムと徹底的なサポートにより、',
    'company.description3': '求職者の転職成功と企業の採用課題解決を実現します。',
    
    // Support Cases
    'cases.title': '支援事例',
    'cases.subtitle': 'SUPPORT CASES',
    'case1.title': 'エンジニア転職成功事例',
    'case1.description': 'AI面接システムを活用し、希望の企業への転職を実現。',
    'case1.result': '転職成功',
    'case2.title': '一般職転職成功事例',
    'case2.description': '徹底的なサポートにより、理想の職場環境を見つけました。',
    'case2.result': '転職成功',
    'case3.title': '企業採用成功事例',
    'case3.description': '質の高い人材を迅速にマッチングし、採用課題を解決。',
    'case3.result': '採用成功',
    
    // Footer
    'footer.company': 'just join',
    'footer.rights': 'All rights reserved.',
    'footer.sns': 'SNS',
    
    // Features
    'features.title': 'justjoinが選ばれる3つの理由',
    'features.reason1.title': '業界最大級のビジネススケール',
    'features.reason1.subtitle': '業界最大級のビジネススケール',
    'features.reason1.description': '業界最大級のスタッフ数、求人数を誇るjustjoinだからこそ、幅広い職種やニーズに対応できます。AI面接システムと徹底的なサポートにより、求職者の転職成功と企業の採用課題解決を実現します。',
    'features.reason2.title': '日本全国からの依頼に対応可能',
    'features.reason2.subtitle': '日本全国からの依頼に対応可能',
    'features.reason2.description': '全都道府県を網羅するサービスネットワークで、各地域のニーズに迅速に対応します。全国での一括対応や、地方拠点や遠隔地での対応など、企業のニーズに合わせた対応が可能です。',
    'features.reason3.title': '要望に合う人材をスピーディーにご紹介',
    'features.reason3.subtitle': '要望に合う人材をスピーディーにご紹介',
    'features.reason3.description': '人材ビジネスに携わること半世紀。長年培ってきたマッチング力を活かし経験やスキルのほか、数値化の難しい相性や適性などをしっかり見極め最適な人材をご紹介します。',
    
    // Job Categories
    'categories.title': '対応職種',
    'categories.subtitle': '事務・営業・研究開発・クリエイティブなどの幅広い職種・業務ラインナップ。短期・短時間からフルタイムまでさまざまな勤務形態に対応可能です。',
    'categories.office.title': '事務・オフィスワーク',
    'categories.office.description': '人事/総務/営業事務/データ入力/OA事務/経理・財務/秘書/受付/レセプト業務/法務・知的財産関連事務/広報/マーケティング/学校事務/大学事務/翻訳/英文事務/貿易事務/金融事務/医療事務/事業企画・立案 など',
    'categories.sales.title': '営業・接客・販売',
    'categories.sales.description': '法人営業/個人営業/コールセンター/インサイドセールス/人材コーディネーター/テレコミュニケーター/接客/カスタマーサポート/セールスエンジニア営業/店頭販売/食品販売/旅程管理 など',
    'categories.creative.title': 'クリエイティブ・土木系',
    'categories.creative.description': 'CAD操作/BIM/CIM/手書トレース/編集/インテリアコーディネーター/設計/広告・DTP・Webデザイン制作/CGクリエーター/ゲームクリエーター/放送・映像機器操作/放送番組などの制作/演出 など',
    'categories.research.title': '臨床開発・研究開発',
    'categories.research.description': '研究職/実験/臨床検査/臨床開発/CRA/医薬情報関連業務/PMS/MR/農林水産業関連業務 など',
    'categories.it.title': 'IT・機械・電気系',
    'categories.it.description': 'CADオペレーター/設計/SE・プログラマー/ソフトウェア開発/ネットワークエンジニア/運用管理/テクニカルサポート/評価・テスティング/手書トレース/試作・実験・評価/情報システム/テクニカルライター/OAインストラクション など',
    'categories.manufacturing.title': '製造・物流・作業系',
    'categories.manufacturing.description': '製品点検・保守/製造/軽作業/包装作業/フォークリフトなどの輸送業務/物流・倉庫業務/ピッキング・仕分け/設備運転・点検・整備/検査/運行管理・配車業務/衛生関連業務/水産加工/マンション・ビル管理業務/建設機械運転 など',
    'categories.other': '上記の職種・業務以外も対応可能です',
    
    // Process
    'process.title': 'ご利用の流れ',
    'process.subtitle': 'ご要望をおうかがいし、最適な人材をスピーディーにご紹介します',
    'process.step1.title': '登録のご依頼',
    'process.step1.description': 'お気軽にお問合せください。ご依頼内容を確認後、速やかにご連絡いたします。',
    'process.step2.title': 'ヒアリング',
    'process.step2.description': 'ご依頼背景や業務内容などを詳しくヒアリングし、ニーズに合わせた人材活用をご提案します。',
    'process.step3.title': '人材の選定・ご紹介',
    'process.step3.description': 'ご依頼内容はもちろん企業との相性や適性を加味したうえで、人材を迅速に選定、ご紹介します。',
    'process.step4.title': 'ご契約・就業開始',
    'process.step4.description': '契約を締結し、ご紹介した人材が貴社で業務を開始します。',
    'process.step5.title': '定期フォロー',
    'process.step5.description': '担当者が人材の就業状況を定期的に確認します。就業上における課題の早期発見・解決を行い、安定就業をサポートします。',
    
    // FAQ
    'faq.title': 'よくあるご質問',
    'faq.q1.question': 'justjoinの利用は無料ですか？',
    'faq.q1.answer': 'はい、求職者様のご利用は完全無料です。登録から求人紹介、面接対策、転職サポートまで、すべて無料でご利用いただけます。',
    'faq.q2.question': '時短勤務や週4日以下の勤務形態の求人はありますか？',
    'faq.q2.answer': 'はい、週4日以下や短時間の勤務形態の求人も多数ございます。あなたのライフスタイルに合わせた働き方ができる求人をご紹介いたします。',
    'faq.q3.question': '登録からどのくらいで求人を紹介してもらえますか？',
    'faq.q3.answer': '登録後、専任担当者があなたの希望条件をヒアリングし、最適な求人を選定してご紹介いたします。通常、登録から数日以内に最初の求人をご紹介することができます。',
    'faq.q4.question': '利用できるサービスにはどのようなものがありますか？',
    'faq.q4.answer': '当社では「求人紹介」「AI面接システム」「転職サポート」「履歴書・職務経歴書の作成支援」「面接対策」などのサービスを無料でご提供しております。あなたの転職活動を徹底的にサポートいたします。',
    'faq.other': 'その他のご質問もお気軽にお問い合わせください',
    'faq.contact': '無料登録はこちら',
  },
  en: {
    'header.login': 'Login',
    'header.register': 'Register',
    'hero.title': '<span class="text-primary">Growth in Japan</span><br>Achievement Platform',
    'hero.subtitle': 'Dedicated staff support your employment<br>Find the perfect job',
    'hero.stats.companies': 'Partner Companies',
    'hero.stats.staff': 'Active Staff',
    'hero.stats.prefectures': 'Prefectures',
    'hero.stats.note1': '*2023 Results',
    'hero.stats.note2': '*As of Dec 2024',
    'hero.stats.note3': 'Available',
    'hero.quickInfo1': 'Easy 30 seconds',
    'hero.quickInfo2': 'Register for free job support',
    'hero.cta1': 'I want to change jobs',
    'hero.cta2': 'I want to gather information',
    'hero.contact': 'Call us',
    'hero.contactHours': 'Weekdays 9:00~19:00 (Excluding weekends and holidays)',
    'hero.appeal.title': 'For Those Who Want to Work',
    'hero.appeal.subtitle': 'With justjoin, you can find a job that matches your preferences',
    'hero.appeal.item1.title': 'Wide Range of Job Listings',
    'hero.appeal.item1.description': 'We offer various job types including office work, sales, R&D, and creative positions.',
    'hero.appeal.item2.title': 'Flexible Work Styles',
    'hero.appeal.item2.description': 'From part-time to full-time, you can work in a way that fits your lifestyle.',
    'hero.appeal.item3.title': 'Comprehensive Support',
    'hero.appeal.item3.description': 'Professional advisors thoroughly support your job search activities.',
    'company.title': 'ABOUT US',
    'company.subtitle': 'About justjoin',
    'company.name': 'Company Name',
    'company.nameValue': 'just join',
    'company.email': 'Email',
    'company.emailValue': 'inside.justjoin@gmail.com',
    'company.description': 'just join operates a job platform connecting job seekers and companies.',
    'company.description2': 'Through AI interview system and thorough support,',
    'company.description3': 'we realize successful career changes for job seekers and solve hiring challenges for companies.',
    'cases.title': 'Support Cases',
    'cases.subtitle': 'SUPPORT CASES',
    'case1.title': 'Engineer Career Change Success',
    'case1.description': 'Successfully changed jobs to desired company using AI interview system.',
    'case1.result': 'Success',
    'case2.title': 'General Position Career Change Success',
    'case2.description': 'Found ideal workplace environment through thorough support.',
    'case2.result': 'Success',
    'case3.title': 'Company Hiring Success',
    'case3.description': 'Quickly matched high-quality talent and solved hiring challenges.',
    'case3.result': 'Success',
    'footer.company': 'just join',
    'footer.rights': 'All rights reserved.',
    'footer.sns': 'SNS',
    'faq.title': 'Frequently Asked Questions',
    'faq.q1.question': 'Is justjoin free to use?',
    'faq.q1.answer': 'Yes, all services for job seekers are completely free. From registration to job introductions, interview preparation, and job search support, everything is free.',
    'faq.q2.question': 'Are there part-time or 4-day work week positions?',
    'faq.q2.answer': 'Yes, we have many positions with 4-day work weeks or shorter hours. We can introduce jobs that match your lifestyle.',
    'faq.q3.question': 'How long does it take to receive job introductions after registration?',
    'faq.q3.answer': 'After registration, a dedicated staff member will interview you about your preferences and select the best jobs for you. Usually, we can introduce the first job within a few days of registration.',
    'faq.q4.question': 'What services are available?',
    'faq.q4.answer': 'We provide free services including "Job Introductions," "AI Interview System," "Job Search Support," "Resume and Career History Creation Support," and "Interview Preparation." We thoroughly support your job search activities.',
    'faq.other': 'Please feel free to contact us with any other questions',
    'faq.contact': 'Free Registration',
    'features.title': '3 Reasons to Choose justjoin',
    'features.reason1.title': 'Industry-Leading Business Scale',
    'features.reason1.subtitle': 'Industry-Leading Business Scale',
    'features.reason1.description': 'With the industry\'s largest number of staff and job listings, justjoin can respond to a wide range of job types and needs. Through AI interview systems and thorough support, we realize successful career changes for job seekers and solve hiring challenges for companies.',
    'features.reason2.title': 'Nationwide Coverage',
    'features.reason2.subtitle': 'Nationwide Coverage',
    'features.reason2.description': 'With a service network covering all 47 prefectures, we respond quickly to regional needs. We can handle unified nationwide support, as well as support for local bases and remote areas, tailored to company needs.',
    'features.reason3.title': 'Quick Introduction of Matching Talent',
    'features.reason3.subtitle': 'Quick Introduction of Matching Talent',
    'features.reason3.description': 'With half a century in the human resources business, we leverage our long-cultivated matching power to carefully assess not only experience and skills, but also hard-to-quantify compatibility and aptitude, to introduce the best talent.',
    'categories.title': 'Job Categories',
    'categories.subtitle': 'A wide range of job types and business lineups including office work, sales, R&D, and creative positions. We support various work styles from short-term and part-time to full-time.',
    'categories.office.title': 'Office Work',
    'categories.office.description': 'HR/General Affairs/Sales Administration/Data Entry/OA Work/Accounting & Finance/Secretary/Reception/Medical Billing/Legal & IP Affairs/Public Relations/Marketing/School Administration/University Administration/Translation/English Office Work/Trade Affairs/Financial Affairs/Medical Affairs/Business Planning & Development, etc.',
    'categories.sales.title': 'Sales, Customer Service & Retail',
    'categories.sales.description': 'Corporate Sales/Individual Sales/Call Center/Inside Sales/HR Coordinator/Telecommunicator/Customer Service/Customer Support/Sales Engineer/Store Sales/Food Sales/Travel Management, etc.',
    'categories.creative.title': 'Creative & Civil Engineering',
    'categories.creative.description': 'CAD Operation/BIM/CIM/Hand Tracing/Editing/Interior Coordinator/Design/Advertising, DTP & Web Design/CG Creator/Game Creator/Broadcast & Video Equipment Operation/Broadcast Program Production/Direction, etc.',
    'categories.research.title': 'Clinical Development & R&D',
    'categories.research.description': 'Research/Experiments/Clinical Testing/Clinical Development/CRA/Pharmaceutical Information/PMS/MR/Agriculture, Forestry & Fisheries, etc.',
    'categories.it.title': 'IT, Mechanical & Electrical',
    'categories.it.description': 'CAD Operator/Design/SE & Programmer/Software Development/Network Engineer/Operations Management/Technical Support/Evaluation & Testing/Hand Tracing/Prototyping, Experiments & Evaluation/Information Systems/Technical Writer/OA Instruction, etc.',
    'categories.manufacturing.title': 'Manufacturing, Logistics & Operations',
    'categories.manufacturing.description': 'Product Inspection & Maintenance/Manufacturing/Light Work/Packaging/Transportation (Forklift, etc.)/Logistics & Warehouse/Picking & Sorting/Equipment Operation, Inspection & Maintenance/Inspection/Traffic Management & Dispatch/Sanitation/Seafood Processing/Building Management/Construction Machinery Operation, etc.',
    'categories.other': 'We can also handle job types and businesses not listed above',
    'process.title': 'How to Use',
    'process.subtitle': 'We listen to your needs and quickly introduce the best talent',
    'process.step1.title': 'Registration Request',
    'process.step1.description': 'Feel free to contact us. After confirming your request, we will contact you promptly.',
    'process.step2.title': 'Hearing',
    'process.step2.description': 'We conduct detailed interviews about your background and business content, and propose talent utilization tailored to your needs.',
    'process.step3.title': 'Talent Selection & Introduction',
    'process.step3.description': 'Taking into account not only your request but also compatibility and aptitude with the company, we quickly select and introduce talent.',
    'process.step4.title': 'Contract & Start of Work',
    'process.step4.description': 'We conclude a contract and the introduced talent begins work at your company.',
    'process.step5.title': 'Regular Follow-up',
    'process.step5.description': 'Our staff regularly checks the employment status of the talent. We support stable employment by early detection and resolution of employment issues.',
  },
  ru: {
    'header.login': 'Войти',
    'header.register': 'Регистрация',
    'hero.title': '<span class="text-primary">Рост в Японии</span><br>Платформа для достижения',
    'hero.subtitle': 'Персональный менеджер поддержит ваше трудоустройство<br>Найдите идеальную работу',
    'hero.stats.companies': 'Компании-партнеры',
    'hero.stats.staff': 'Активный персонал',
    'hero.stats.prefectures': 'Префектуры',
    'hero.stats.note1': '*Результаты 2023',
    'hero.stats.note2': '*По состоянию на дек 2024',
    'hero.stats.note3': 'Доступно',
    'hero.quickInfo1': 'Легко за 30 секунд',
    'hero.quickInfo2': 'Зарегистрируйтесь для бесплатной поддержки',
    'hero.cta1': 'Хочу сменить работу',
    'hero.cta2': 'Хочу собрать информацию',
    'hero.contact': 'Позвоните нам',
    'hero.contactHours': 'Будни 9:00~19:00 (кроме выходных и праздников)',
    'hero.appeal.title': 'Для тех, кто хочет работать',
    'hero.appeal.subtitle': 'С justjoin вы можете найти работу, соответствующую вашим предпочтениям',
    'hero.appeal.item1.title': 'Широкий спектр вакансий',
    'hero.appeal.item1.description': 'Мы предлагаем различные типы работы, включая офисную работу, продажи, НИОКР и творческие должности.',
    'hero.appeal.item2.title': 'Гибкий график работы',
    'hero.appeal.item2.description': 'От частичной занятости до полной, вы можете работать так, как вам удобно.',
    'hero.appeal.item3.title': 'Комплексная поддержка',
    'hero.appeal.item3.description': 'Профессиональные консультанты тщательно поддерживают ваши поиски работы.',
    'company.title': 'О НАС',
    'company.subtitle': 'О justjoin',
    'company.name': 'Название компании',
    'company.nameValue': 'just join',
    'company.email': 'Электронная почта',
    'company.emailValue': 'inside.justjoin@gmail.com',
    'company.description': 'just join управляет платформой для трудоустройства, соединяющей соискателей и компании.',
    'company.description2': 'Через систему AI-интервью и тщательную поддержку,',
    'company.description3': 'мы реализуем успешные карьерные переходы для соискателей и решаем проблемы найма для компаний.',
    'cases.title': 'Примеры поддержки',
    'cases.subtitle': 'ПРИМЕРЫ ПОДДЕРЖКИ',
    'case1.title': 'Успешный карьерный переход инженера',
    'case1.description': 'Успешно сменил работу в желаемую компанию, используя систему AI-интервью.',
    'case1.result': 'Успех',
    'case2.title': 'Успешный карьерный переход на общую должность',
    'case2.description': 'Нашел идеальную рабочую среду благодаря тщательной поддержке.',
    'case2.result': 'Успех',
    'case3.title': 'Успешный найм компании',
    'case3.description': 'Быстро подобрал качественный талант и решил проблемы найма.',
    'case3.result': 'Успех',
    'footer.company': 'just join',
    'footer.rights': 'Все права защищены.',
    'footer.sns': 'SNS',
    'faq.title': 'Часто задаваемые вопросы',
    'faq.q1.question': 'Бесплатно ли использование justjoin?',
    'faq.q1.answer': 'Да, все услуги для соискателей полностью бесплатны. От регистрации до подбора вакансий, подготовки к собеседованию и поддержки поиска работы - все бесплатно.',
    'faq.q2.question': 'Есть ли вакансии с неполным рабочим днем или 4-дневной рабочей неделей?',
    'faq.q2.answer': 'Да, у нас много вакансий с 4-дневной рабочей неделей или сокращенным рабочим днем. Мы можем предложить работу, соответствующую вашему образу жизни.',
    'faq.q3.question': 'Как долго ждать предложений о работе после регистрации?',
    'faq.q3.answer': 'После регистрации персональный менеджер проведет собеседование о ваших предпочтениях и подберет лучшие вакансии. Обычно мы можем предложить первую вакансию в течение нескольких дней после регистрации.',
    'faq.q4.question': 'Какие услуги доступны?',
    'faq.q4.answer': 'Мы предоставляем бесплатные услуги, включая "Подбор вакансий," "Система AI-интервью," "Поддержка поиска работы," "Помощь в создании резюме и истории карьеры" и "Подготовка к собеседованию." Мы тщательно поддерживаем ваши поиски работы.',
    'faq.other': 'Пожалуйста, не стесняйтесь обращаться к нам с любыми другими вопросами',
    'faq.contact': 'Бесплатная регистрация',
    'features.title': '3 причины выбрать justjoin',
    'features.reason1.title': 'Крупнейший масштаб бизнеса в отрасли',
    'features.reason1.subtitle': 'Крупнейший масштаб бизнеса в отрасли',
    'features.reason1.description': 'Благодаря крупнейшему в отрасли количеству персонала и вакансий, justjoin может отвечать на широкий спектр типов работы и потребностей. Через системы AI-интервью и тщательную поддержку мы реализуем успешные карьерные переходы для соискателей и решаем проблемы найма для компаний.',
    'features.reason2.title': 'Охват всей страны',
    'features.reason2.subtitle': 'Охват всей страны',
    'features.reason2.description': 'С сервисной сетью, охватывающей все 47 префектур, мы быстро реагируем на региональные потребности. Мы можем обрабатывать единую общенациональную поддержку, а также поддержку для местных баз и удаленных районов, адаптированную к потребностям компаний.',
    'features.reason3.title': 'Быстрое представление подходящего таланта',
    'features.reason3.subtitle': 'Быстрое представление подходящего таланта',
    'features.reason3.description': 'С полувековым опытом в бизнесе человеческих ресурсов, мы используем нашу долгосрочно развитую силу подбора, чтобы тщательно оценить не только опыт и навыки, но и трудно поддающуюся количественной оценке совместимость и способности, чтобы представить лучший талант.',
    'categories.title': 'Категории работы',
    'categories.subtitle': 'Широкий спектр типов работы и бизнес-линеек, включая офисную работу, продажи, НИОКР и творческие должности. Мы поддерживаем различные стили работы от краткосрочной и частичной занятости до полной.',
    'categories.office.title': 'Офисная работа',
    'categories.office.description': 'HR/Общие дела/Администрация продаж/Ввод данных/OA работа/Бухгалтерия и финансы/Секретарь/Приемная/Медицинское выставление счетов/Юридические и IP дела/Связи с общественностью/Маркетинг/Школьная администрация/Университетская администрация/Перевод/Английская офисная работа/Торговые дела/Финансовые дела/Медицинские дела/Бизнес-планирование и развитие, и т.д.',
    'categories.sales.title': 'Продажи, обслуживание клиентов и розничная торговля',
    'categories.sales.description': 'Корпоративные продажи/Индивидуальные продажи/Колл-центр/Внутренние продажи/HR-координатор/Телекоммуникатор/Обслуживание клиентов/Поддержка клиентов/Инженер по продажам/Продажи в магазине/Продажи продуктов питания/Управление путешествиями, и т.д.',
    'categories.creative.title': 'Творчество и гражданское строительство',
    'categories.creative.description': 'Работа с CAD/BIM/CIM/Ручное трассирование/Редактирование/Интерьерный координатор/Дизайн/Реклама, DTP и веб-дизайн/CG-создатель/Создатель игр/Работа с вещательным и видеооборудованием/Производство вещательных программ/Режиссура, и т.д.',
    'categories.research.title': 'Клиническая разработка и НИОКР',
    'categories.research.description': 'Исследования/Эксперименты/Клиническое тестирование/Клиническая разработка/CRA/Фармацевтическая информация/PMS/MR/Сельское хозяйство, лесное хозяйство и рыболовство, и т.д.',
    'categories.it.title': 'IT, механическое и электрическое',
    'categories.it.description': 'Оператор CAD/Дизайн/SE и программист/Разработка программного обеспечения/Сетевой инженер/Управление операциями/Техническая поддержка/Оценка и тестирование/Ручное трассирование/Прототипирование, эксперименты и оценка/Информационные системы/Технический писатель/OA-инструкция, и т.д.',
    'categories.manufacturing.title': 'Производство, логистика и операции',
    'categories.manufacturing.description': 'Инспекция и обслуживание продукции/Производство/Легкая работа/Упаковка/Транспортировка (вилочный погрузчик и т.д.)/Логистика и склад/Комплектация и сортировка/Эксплуатация, инспекция и обслуживание оборудования/Инспекция/Управление движением и диспетчеризация/Санитария/Обработка морепродуктов/Управление зданиями/Эксплуатация строительной техники, и т.д.',
    'categories.other': 'Мы также можем обрабатывать типы работы и бизнесы, не перечисленные выше',
    'process.title': 'Как использовать',
    'process.subtitle': 'Мы слушаем ваши потребности и быстро представляем лучший талант',
    'process.step1.title': 'Запрос на регистрацию',
    'process.step1.description': 'Не стесняйтесь обращаться к нам. После подтверждения вашего запроса мы свяжемся с вами незамедлительно.',
    'process.step2.title': 'Собеседование',
    'process.step2.description': 'Мы проводим подробные собеседования о вашем фоне и бизнес-содержании и предлагаем использование таланта, адаптированное к вашим потребностям.',
    'process.step3.title': 'Отбор и представление таланта',
    'process.step3.description': 'Учитывая не только ваш запрос, но и совместимость и способности с компанией, мы быстро отбираем и представляем талант.',
    'process.step4.title': 'Контракт и начало работы',
    'process.step4.description': 'Мы заключаем контракт, и представленный талант начинает работу в вашей компании.',
    'process.step5.title': 'Регулярное наблюдение',
    'process.step5.description': 'Наш персонал регулярно проверяет статус занятости таланта. Мы поддерживаем стабильную занятость путем раннего обнаружения и решения проблем занятости.',
  },
  uz: {
    'header.login': 'Kirish',
    'header.register': 'Ro\'yxatdan o\'tish',
    'hero.title': '<span class="text-primary">Yaponiyada o\'sish</span><br>Amalga oshirish platformasi',
    'hero.subtitle': 'Maxsus xodim sizning ishga kirishingizni qo\'llab-quvvatlaydi<br>Eng mos ishni toping',
    'hero.stats.companies': 'Hamkor kompaniyalar',
    'hero.stats.staff': 'Faol xodimlar',
    'hero.stats.prefectures': 'Prefekturalar',
    'hero.stats.note1': '*2023 natijalari',
    'hero.stats.note2': '*2024 yil dekabr holatiga',
    'hero.stats.note3': 'Mavjud',
    'hero.quickInfo1': 'Oson 30 soniya',
    'hero.quickInfo2': 'Bepul ish qo\'llab-quvvatlash uchun ro\'yxatdan o\'ting',
    'hero.cta1': 'Ishni o\'zgartirmoqchiman',
    'hero.cta2': 'Ma\'lumot to\'plamoqchiman',
    'hero.contact': 'Bizga qo\'ng\'iroq qiling',
    'hero.contactHours': 'Ish kunlari 9:00~19:00 (dam olish kunlari va bayramlar bundan mustasno)',
    'hero.appeal.title': 'Ishlamoqchi bo\'lganlar uchun',
    'hero.appeal.subtitle': 'justjoin bilan siz o\'zingizga mos ishni topishingiz mumkin',
    'hero.appeal.item1.title': 'Keng ish ro\'yxati',
    'hero.appeal.item1.description': 'Biz ofis ishi, sotish, R&D va ijodiy lavozimlar kabi turli xil ish turlarini taklif qilamiz.',
    'hero.appeal.item2.title': 'Moslashuvchan ish uslublari',
    'hero.appeal.item2.description': 'Qisman ishdan to\'liq ishgacha, siz o\'zingizning hayot tarzingizga mos keladigan tarzda ishlashingiz mumkin.',
    'hero.appeal.item3.title': 'To\'liq qo\'llab-quvvatlash',
    'hero.appeal.item3.description': 'Professional maslahatchilar sizning ish qidirish faoliyatingizni to\'liq qo\'llab-quvvatlaydi.',
    'company.title': 'BIZ HAQIMIZDA',
    'company.subtitle': 'justjoin haqida',
    'company.name': 'Kompaniya nomi',
    'company.nameValue': 'just join',
    'company.email': 'Elektron pochta',
    'company.emailValue': 'inside.justjoin@gmail.com',
    'company.description': 'just join ish qidiruvchilar va kompaniyalarni bog\'laydigan ish platformasini boshqaradi.',
    'company.description2': 'AI intervyu tizimi va to\'liq qo\'llab-quvvatlash orqali,',
    'company.description3': 'biz ish qidiruvchilar uchun muvaffaqiyatli martaba o\'zgarishlarini va kompaniyalar uchun ishga olish muammolarini hal qilamiz.',
    'cases.title': 'Qo\'llab-quvvatlash misollari',
    'cases.subtitle': 'QO\'LLAB-QUVVATLASH MISOLLARI',
    'case1.title': 'Muhandis martaba o\'zgarishi muvaffaqiyati',
    'case1.description': 'AI intervyu tizimidan foydalanib, istagan kompaniyaga muvaffaqiyatli o\'tdi.',
    'case1.result': 'Muvaffaqiyat',
    'case2.title': 'Umumiy lavozim martaba o\'zgarishi muvaffaqiyati',
    'case2.description': 'To\'liq qo\'llab-quvvatlash orqali ideal ish joyini topdi.',
    'case2.result': 'Muvaffaqiyat',
    'case3.title': 'Kompaniya ishga olish muvaffaqiyati',
    'case3.description': 'Yuqori sifatli talantlarni tezda moslashtirdi va ishga olish muammolarini hal qildi.',
    'case3.result': 'Muvaffaqiyat',
    'footer.company': 'just join',
    'footer.rights': 'Barcha huquqlar himoyalangan.',
    'footer.sns': 'SNS',
    'faq.title': 'Tez-tez so\'raladigan savollar',
    'faq.q1.question': 'justjoin foydalanish bepulmi?',
    'faq.q1.answer': 'Ha, ish qidiruvchilar uchun barcha xizmatlar butunlay bepul. Ro\'yxatdan o\'tishdan ish takliflarigacha, intervyuga tayyorgarlik va ish qidirish qo\'llab-quvvatlashigacha, hammasi bepul.',
    'faq.q2.question': 'Qisman ish yoki 4 kunlik ish haftasi lavozimlari bormi?',
    'faq.q2.answer': 'Ha, bizda 4 kunlik ish haftasi yoki qisqa soatli ko\'plab lavozimlar mavjud. Biz sizning hayot tarzingizga mos keladigan ishlarni taklif qilishimiz mumkin.',
    'faq.q3.question': 'Ro\'yxatdan o\'tgandan keyin ish takliflarini qancha vaqt ichida olish mumkin?',
    'faq.q3.answer': 'Ro\'yxatdan o\'tgandan so\'ng, maxsus xodim sizning afzalliklaringiz haqida suhbat oladi va siz uchun eng yaxshi ishlarni tanlaydi. Odatda, ro\'yxatdan o\'tishdan bir necha kun ichida birinchi ishni taklif qilishimiz mumkin.',
    'faq.q4.question': 'Qanday xizmatlar mavjud?',
    'faq.q4.answer': 'Biz "Ish takliflari," "AI intervyu tizimi," "Ish qidirish qo\'llab-quvvatlash," "Rezyume va martaba tarixi yaratish qo\'llab-quvvatlash" va "Intervyuga tayyorgarlik" kabi bepul xizmatlarni taqdim etamiz. Biz sizning ish qidirish faoliyatingizni to\'liq qo\'llab-quvvatlaymiz.',
    'faq.other': 'Iltimos, boshqa savollar bilan bizga murojaat qiling',
    'faq.contact': 'Bepul ro\'yxatdan o\'tish',
    'features.title': 'justjoin tanlash uchun 3 sabab',
    'features.reason1.title': 'Sanoatda eng katta biznes miqyosi',
    'features.reason1.subtitle': 'Sanoatda eng katta biznes miqyosi',
    'features.reason1.description': 'Sanoatda eng katta xodimlar va ish ro\'yxatlari soni bilan, justjoin turli xil ish turlari va ehtiyojlarga javob bera oladi. AI intervyu tizimlari va to\'liq qo\'llab-quvvatlash orqali, biz ish qidiruvchilar uchun muvaffaqiyatli martaba o\'zgarishlarini amalga oshiramiz va kompaniyalar uchun ishga olish muammolarini hal qilamiz.',
    'features.reason2.title': 'Butun mamlakat qamrovi',
    'features.reason2.subtitle': 'Butun mamlakat qamrovi',
    'features.reason2.description': 'Barcha 47 prefekturani qamrab olgan xizmat tarmog\'i bilan, biz mintaqaviy ehtiyojlarga tez javob beramiz. Biz birlashtirilgan milliy qo\'llab-quvvatlashni, shuningdek, mahalliy bazalar va uzoq joylar uchun qo\'llab-quvvatlashni, kompaniya ehtiyojlariga moslashtirilgan holda boshqarishimiz mumkin.',
    'features.reason3.title': 'Mos keladigan talantni tezda taklif qilish',
    'features.reason3.subtitle': 'Mos keladigan talantni tezda taklif qilish',
    'features.reason3.description': 'Yarim asrlik inson resurslari biznesi bilan, biz uzoq muddatli rivojlantirilgan moslashtirish kuchimizdan foydalanib, nafaqat tajriba va ko\'nikmalarni, balki miqdoriy baholash qiyin bo\'lgan mos kelish va qobiliyatni ham diqqat bilan baholaymiz, eng yaxshi talantni taklif qilish uchun.',
    'categories.title': 'Ish kategoriyalari',
    'categories.subtitle': 'Ofis ishi, sotish, R&D va ijodiy lavozimlarni o\'z ichiga olgan keng ish turlari va biznes liniyalari. Biz qisqa muddatli va qisman ishdan to\'liq ishgacha turli xil ish uslublarini qo\'llab-quvvatlaymiz.',
    'categories.office.title': 'Ofis ishi',
    'categories.office.description': 'HR/Umumiy ishlar/Sotish ma\'muriyati/Ma\'lumot kiritish/OA ishi/Buxgalteriya va moliya/Kotiba/Qabulxona/Meditsina hisob-kitoblari/Yuridik va IP ishlari/Jamoat aloqalari/Marketing/Maktab ma\'muriyati/Universitet ma\'muriyati/Tarjima/Ingliz ofis ishi/Savdo ishlari/Moliyaviy ishlar/Meditsina ishlari/Biznes rejalashtirish va rivojlantirish, va boshqalar.',
    'categories.sales.title': 'Sotish, mijozlarga xizmat ko\'rsatish va chakana savdo',
    'categories.sales.description': 'Korporativ sotish/Individual sotish/Qo\'ng\'iroq markazi/Ichki sotish/HR koordinatori/Telekommunikator/Mijozlarga xizmat ko\'rsatish/Mijozlar qo\'llab-quvvatlash/Sotish muhandisi/Do\'kon sotishi/Oziq-ovqat sotishi/Sayohlik boshqaruvi, va boshqalar.',
    'categories.creative.title': 'Ijodiy va fuqarolik muhandisligi',
    'categories.creative.description': 'CAD operatsiyasi/BIM/CIM/Qo\'lda kuzatish/Tahrirlash/Interyer koordinatori/Dizayn/Reklama, DTP va veb-dizayn/CG yaratuvchisi/O\'yin yaratuvchisi/Radioeshittirish va video uskunalar operatsiyasi/Radioeshittirish dasturlari ishlab chiqarish/Rejissyorlik, va boshqalar.',
    'categories.research.title': 'Klinik rivojlantirish va R&D',
    'categories.research.description': 'Tadqiqot/Eksperimentlar/Klinik test/Klinik rivojlantirish/CRA/Farmatsevtika ma\'lumotlari/PMS/MR/Qishloq xo\'jaligi, o\'rmon xo\'jaligi va baliqchilik, va boshqalar.',
    'categories.it.title': 'IT, mexanik va elektr',
    'categories.it.description': 'CAD operatori/Dizayn/SE va dasturchi/Dasturiy ta\'minot rivojlantirish/Tarmoq muhandisi/Operatsiyalar boshqaruvi/Texnik qo\'llab-quvvatlash/Baholash va test/Qo\'lda kuzatish/Prototiplash, eksperimentlar va baholash/Axborot tizimlari/Texnik yozuvchi/OA ko\'rsatma, va boshqalar.',
    'categories.manufacturing.title': 'Ishlab chiqarish, logistika va operatsiyalar',
    'categories.manufacturing.description': 'Mahsulot tekshiruvi va texnik xizmat/Ishlab chiqarish/Yengil ish/Qadoqlash/Transport (forklift va boshqalar)/Logistika va ombor/Tanlash va saralash/Uskuna operatsiyasi, tekshiruvi va texnik xizmati/Tekshiruv/Traffic boshqaruvi va dispatch/Sanitariya/Dengiz mahsulotlari qayta ishlash/Bino boshqaruvi/Qurilish mashinalari operatsiyasi, va boshqalar.',
    'categories.other': 'Biz yuqorida sanab o\'tilmagan ish turlari va bizneslarni ham boshqarishimiz mumkin',
    'process.title': 'Qanday foydalanish',
    'process.subtitle': 'Biz sizning ehtiyojlaringizni tinglaymiz va eng yaxshi talantni tezda taklif qilamiz',
    'process.step1.title': 'Ro\'yxatdan o\'tish so\'rovi',
    'process.step1.description': 'Bizga murojaat qilishdan tortinmang. So\'rovingizni tasdiqlagandan so\'ng, biz darhol siz bilan bog\'lanamiz.',
    'process.step2.title': 'Suhbat',
    'process.step2.description': 'Biz sizning fon va biznes mazmuningiz haqida batafsil suhbatlar olib boramiz va sizning ehtiyojlaringizga moslashtirilgan talantdan foydalanishni taklif qilamiz.',
    'process.step3.title': 'Talant tanlash va taklif qilish',
    'process.step3.description': 'Nafaqat so\'rovingizni, balki kompaniya bilan mos kelish va qobiliyatni ham hisobga olgan holda, biz tezda talantni tanlaymiz va taklif qilamiz.',
    'process.step4.title': 'Shartnoma va ish boshlash',
    'process.step4.description': 'Biz shartnoma tuzamiz va taklif qilingan talant sizning kompaniyangizda ishni boshlaydi.',
    'process.step5.title': 'Muntazam kuzatish',
    'process.step5.description': 'Bizning xodimlarimiz talantning ish holatini muntazam tekshiradi. Biz ish muammolarini erta aniqlash va hal qilish orqali barqaror ishni qo\'llab-quvvatlaymiz.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ja');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

