// 国連加盟国193カ国のリスト（英語名）
export const UN_MEMBER_COUNTRIES = [
  "Japan", "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
  "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
  "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia",
  "Comoros", "Congo", "Democratic Republic of the Congo", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba",
  "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
  "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji",
  "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada",
  "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland",
  "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica",
  "Jordan", "Kazakhstan", "Kenya", "Kiribati", "North Korea", "Korea", "Kuwait", "Kyrgyzstan", "Laos",
  "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
  "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco",
  "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua",
  "Niger", "Nigeria", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama",
  "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar",
  "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
  "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
  "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan",
  "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Tajikistan",
  "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
  "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay",
  "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
].sort();

// 国籍の日本語名マッピング
export const NATIONALITY_NAMES: { [key: string]: string } = {
  "Japan": "日本",
  "Afghanistan": "アフガニスタン",
  "Albania": "アルバニア",
  "Algeria": "アルジェリア",
  "Andorra": "アンドラ",
  "Angola": "アンゴラ",
  "Antigua and Barbuda": "アンティグア・バーブーダ",
  "Argentina": "アルゼンチン",
  "Armenia": "アルメニア",
  "Australia": "オーストラリア",
  "Austria": "オーストリア",
  "Azerbaijan": "アゼルバイジャン",
  "Bahamas": "バハマ",
  "Bahrain": "バーレーン",
  "Bangladesh": "バングラデシュ",
  "Barbados": "バルバドス",
  "Belarus": "ベラルーシ",
  "Belgium": "ベルギー",
  "Belize": "ベリーズ",
  "Benin": "ベナン",
  "Bhutan": "ブータン",
  "Bolivia": "ボリビア",
  "Bosnia and Herzegovina": "ボスニア・ヘルツェゴビナ",
  "Botswana": "ボツワナ",
  "Brazil": "ブラジル",
  "Brunei": "ブルネイ",
  "Bulgaria": "ブルガリア",
  "Burkina Faso": "ブルキナファソ",
  "Burundi": "ブルンジ",
  "Cambodia": "カンボジア",
  "Cameroon": "カメルーン",
  "Canada": "カナダ",
  "Cape Verde": "カーボベルデ",
  "Central African Republic": "中央アフリカ共和国",
  "Chad": "チャド",
  "Chile": "チリ",
  "China": "中国",
  "Colombia": "コロンビア",
  "Comoros": "コモロ",
  "Congo": "コンゴ",
  "Democratic Republic of the Congo": "コンゴ民主共和国",
  "Costa Rica": "コスタリカ",
  "Cote d'Ivoire": "コートジボワール",
  "Croatia": "クロアチア",
  "Cuba": "キューバ",
  "Cyprus": "キプロス",
  "Czech Republic": "チェコ共和国",
  "Denmark": "デンマーク",
  "Djibouti": "ジブチ",
  "Dominica": "ドミニカ",
  "Dominican Republic": "ドミニカ共和国",
  "Ecuador": "エクアドル",
  "Egypt": "エジプト",
  "El Salvador": "エルサルバドル",
  "Equatorial Guinea": "赤道ギニア",
  "Eritrea": "エリトリア",
  "Estonia": "エストニア",
  "Eswatini": "エスワティニ",
  "Ethiopia": "エチオピア",
  "Fiji": "フィジー",
  "Finland": "フィンランド",
  "France": "フランス",
  "Gabon": "ガボン",
  "Gambia": "ガンビア",
  "Georgia": "ジョージア",
  "Germany": "ドイツ",
  "Ghana": "ガーナ",
  "Greece": "ギリシャ",
  "Grenada": "グレナダ",
  "Guatemala": "グアテマラ",
  "Guinea": "ギニア",
  "Guinea-Bissau": "ギニアビサウ",
  "Guyana": "ガイアナ",
  "Haiti": "ハイチ",
  "Honduras": "ホンジュラス",
  "Hungary": "ハンガリー",
  "Iceland": "アイスランド",
  "India": "インド",
  "Indonesia": "インドネシア",
  "Iran": "イラン",
  "Iraq": "イラク",
  "Ireland": "アイルランド",
  "Israel": "イスラエル",
  "Italy": "イタリア",
  "Jamaica": "ジャマイカ",
  "Jordan": "ヨルダン",
  "Kazakhstan": "カザフスタン",
  "Kenya": "ケニア",
  "Kiribati": "キリバス",
  "North Korea": "北朝鮮",
  "Korea": "韓国",
  "Kuwait": "クウェート",
  "Kyrgyzstan": "キルギス",
  "Laos": "ラオス",
  "Latvia": "ラトビア",
  "Lebanon": "レバノン",
  "Lesotho": "レソト",
  "Liberia": "リベリア",
  "Libya": "リビア",
  "Liechtenstein": "リヒテンシュタイン",
  "Lithuania": "リトアニア",
  "Luxembourg": "ルクセンブルク",
  "Madagascar": "マダガスカル",
  "Malawi": "マラウィ",
  "Malaysia": "マレーシア",
  "Maldives": "モルディブ",
  "Mali": "マリ",
  "Malta": "マルタ",
  "Marshall Islands": "マーシャル諸島",
  "Mauritania": "モーリタニア",
  "Mauritius": "モーリシャス",
  "Mexico": "メキシコ",
  "Micronesia": "ミクロネシア",
  "Moldova": "モルドバ",
  "Monaco": "モナコ",
  "Mongolia": "モンゴル",
  "Montenegro": "モンテネグロ",
  "Morocco": "モロッコ",
  "Mozambique": "モザンビーク",
  "Myanmar": "ミャンマー",
  "Namibia": "ナミビア",
  "Nauru": "ナウル",
  "Nepal": "ネパール",
  "Netherlands": "オランダ",
  "New Zealand": "ニュージーランド",
  "Nicaragua": "ニカラグア",
  "Niger": "ニジェール",
  "Nigeria": "ナイジェリア",
  "North Macedonia": "北マケドニア",
  "Norway": "ノルウェー",
  "Oman": "オマーン",
  "Pakistan": "パキスタン",
  "Palau": "パラオ",
  "Panama": "パナマ",
  "Papua New Guinea": "パプアニューギニア",
  "Paraguay": "パラグアイ",
  "Peru": "ペルー",
  "Philippines": "フィリピン",
  "Poland": "ポーランド",
  "Portugal": "ポルトガル",
  "Qatar": "カタール",
  "Romania": "ルーマニア",
  "Russia": "ロシア",
  "Rwanda": "ルワンダ",
  "Saint Kitts and Nevis": "セントキッツ・ネイビス",
  "Saint Lucia": "セントルシア",
  "Saint Vincent and the Grenadines": "セントビンセント・グレナディーン",
  "Samoa": "サモア",
  "San Marino": "サンマリノ",
  "Sao Tome and Principe": "サントメ・プリンシペ",
  "Saudi Arabia": "サウジアラビア",
  "Senegal": "セネガル",
  "Serbia": "セルビア",
  "Seychelles": "セーシェル",
  "Sierra Leone": "シエラレオネ",
  "Singapore": "シンガポール",
  "Slovakia": "スロバキア",
  "Slovenia": "スロベニア",
  "Solomon Islands": "ソロモン諸島",
  "Somalia": "ソマリア",
  "South Africa": "南アフリカ",
  "South Sudan": "南スーダン",
  "Spain": "スペイン",
  "Sri Lanka": "スリランカ",
  "Sudan": "スーダン",
  "Suriname": "スリナム",
  "Sweden": "スウェーデン",
  "Switzerland": "スイス",
  "Syria": "シリア",
  "Tajikistan": "タジキスタン",
  "Tanzania": "タンザニア",
  "Thailand": "タイ",
  "Timor-Leste": "東ティモール",
  "Togo": "トーゴ",
  "Tonga": "トンガ",
  "Trinidad and Tobago": "トリニダード・トバゴ",
  "Tunisia": "チュニジア",
  "Turkey": "トルコ",
  "Turkmenistan": "トルクメニスタン",
  "Tuvalu": "ツバル",
  "Uganda": "ウガンダ",
  "Ukraine": "ウクライナ",
  "United Arab Emirates": "アラブ首長国連邦",
  "United Kingdom": "イギリス",
  "United States": "アメリカ合衆国",
  "Uruguay": "ウルグアイ",
  "Uzbekistan": "ウズベキスタン",
  "Vanuatu": "バヌアツ",
  "Vatican City": "バチカン",
  "Venezuela": "ベネズエラ",
  "Vietnam": "ベトナム",
  "Yemen": "イエメン",
  "Zambia": "ザンビア",
  "Zimbabwe": "ジンバブエ"
}; 