// スキルシートで使用される全てのスキルのリスト
export const ALL_SKILLS = [
  'Windows',
  'MacOS',
  'Linux',
  'Photoshop',
  'Illustrator',
  'Webサーバ（構築、運用）',
  'メールサーバ（構築、運用）',
  'DBサーバ（構築、運用）',
  'DNSサーバ（構築、運用）',
  'N/W設計',
  'N/W構築',
  'N/W調査',
  'N/W監視',
  'DB2',
  'SQL Server',
  'Oracle',
  'MySQL',
  'PostgreSQL',
  'プログラマ',
  'SE',
  'リーダー',
  'マネージャー',
  'C / C++',
  'C#',
  'VB.NET',
  'JAVA',
  'JavaScript ',
  'PHP',
  'Python',
  'Ruby',
  'Swift',
  'Objective-C',
  'HTML / HTML5',
  'CSS / CSS3',
  'R',
  'ASP.NET (Web Forms)',
  'ASP.NET (Core) MVC',
  'jQuery',
  'Bootstrap',
  'Tailwind',
  'ReactJS',
  'VueJS',
  'Laravel',
  '要件定義',
  '外部設計/基本設計',
  '内部設計/詳細設計',
  '検証試験',
  'セキュリティ試験',
  '負荷試験',
  'MS-WORD',
  'MS-EXCEL',
  'MS-Access',
  'MS-PowerPoint',
  'InDesiｇn',
  'Dreamweaver',
  'Fireworks',
  'MAYA',
  'Studio Design',
  'Figma',
  'Visual Studio / VSCode',
  'Git / SVN',
  'Backlog / Redmine',
  'Notion',
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'IBM Cloud (Bluemix)',
  'W3Schools',
  'タッチタイピング',
  'パソコン利用歴'
].sort(); 